services:
  redis:
    image: bitnamilegacy/redis:8.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnamilegacy/redis/data
    environment:
      - REDIS_PASSWORD
  mongo:
    image: mongo:8.2
    entrypoint: ["/mongo-entrypoint.sh"]
    command: mongod --config /etc/mongod.conf
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./mongo-entrypoint.sh:/mongo-entrypoint.sh:ro
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  mongo-search:
    image: mongodb/mongodb-community-search:latest
    entrypoint: ["/mongot-entrypoint.sh"]
    ports:
      - "27028:27028"
      - "9946:9946"
    volumes:
      - mongo_search_data:/data/mongot
      - ./mongot.conf:/mongot-community/config.default.yml:ro
      - ./mongot-entrypoint.sh:/mongot-entrypoint.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   command: deno task dev
  #   environment:
  #     MONGO_URL: ${MONGO_URL}
  #     SECRET_KEY: ${SECRET_KEY}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #   volumes:
  #     - ./backend:/app


volumes:
  mongo_data:
  mongo_search_data:
  redis_data:
