services:
  redis:
    image: bitnamilegacy/redis:8.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnamilegacy/redis/data
    environment:
      - REDIS_PASSWORD
  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: deno task dev
    environment:
      MONGO_URL: ${MONGO_URL}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./backend:/app


volumes:
  mongo_data:
  redis_data: